name: Phpunit

on:
  - push
  - pull_request

jobs:
  phpcs:
    runs-on: ubuntu-latest


    name: phpcs - PHP 8.3


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'


      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction


      - name: Run phpcs
        run: ./vendor/bin/phpcs

  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: ['8.0', '8.1', '8.2', '8.3']
        laravel: ['9.*', '10.*', '11.*', '13.*']
        exclude:
          - php: '8.0'
            laravel: 10.*
          - php: '8.0'
            laravel: 11.*
          - php: '8.1'
            laravel: 11.*
          - laravel: 13.*
            php: '8.0'
          - laravel: 13.*
            php: '8.1'
          - laravel: 13.*
            php: '8.2'


    name: tests - PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}


    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 5


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug


      - name: Install dependencies
        run: |
          COMPOSER_MEMORY_LIMIT=-1 composer require "illuminate/queue:${{ matrix.laravel }}" --no-update
          composer update --prefer-dist --no-interaction


      - name: Run phpunit tests
        run: ./vendor/bin/phpunit --coverage-clover ./clover.xml


      - name: Send coverage
        if: 'success() || failure()'
        run: |
          composer global require scrutinizer/ocular
          ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover ./clover.xml
